version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - ML_SERVER_URL=${ML_SERVER_URL}
      - SECRET_KEY=${SECRET_KEY}
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
