name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  MONGO_DB_HOST: ${{ secrets.MONGO_DB_HOST }}
  MONGO_DB_PORT: ${{ secrets.MONGO_DB_PORT }}
  MONGO_DB_USER: ${{ secrets.MONGO_DB_USER }}
  MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
  MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  test_app:
    name: Test on Python 3.11
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: "6.0"
          mongodb-replica-set: test-rs
          mongodb-port: 27017

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pipenv
          pipenv sync --dev --python $(which python)
          pipenv shell --fancy --python $(which python)
          pipenv run python -m pip install pytest

      - name: Run tests
        run: |
          pipenv run python -m coverage run -m pytest
          pipenv run python -m coverage report --fail-under=80